package pl.exsio.gol.model;

import javax.swing.*;
import java.awt.*;

public final class Cell extends javax.swing.JPanel {


    private boolean populated;

    /**
     * Creates new form Cell
     */
    public Cell() {

        initComponents();
        this.setPopulated(false);
        this.addMouseListener(new CellListener(this));

    }

    public void setPopulated(boolean p) {

        this.populated = p;
        this.update();

    }

    public boolean isPopulated() {

        return this.populated;

    }

    private void update() {
        new SwingWorker() {
            @Override
            protected Object doInBackground() throws Exception {
                if (populated) setBackground(Color.yellow);
                else setBackground(Color.lightGray);
                return null;
            }
        }.execute();


    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setMaximumSize(new java.awt.Dimension(10, 10));
        setMinimumSize(new java.awt.Dimension(10, 10));
        setPreferredSize(new java.awt.Dimension(10, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 10, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 10, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
